.github/workflows/ghcr.yml

diff --git a/.github/workflows/ghcr.yml b/.github/workflows/ghcr.yml
--- a/.github/workflows/ghcr.yml
+++ b/.github/workflows/ghcr.yml
@@ -129,7 +129,15 @@ jobs:
           git checkout -b 0889970d17 0889970d1790a2617e69f253221b8bd7626e51dc
           # patch OpenROAD
           #git am ../openlane_spo_d1f0b60d7b31393ec0afb8f96e1ca02bb465b3fc.patch
-          patch -p1 < ../.github/workflows/openlane_spo_ol1.patch
+          if patch -p1 < ../.github/workflows/openlane_spo_ol1.patch
+          then
+            true
+          elif patch -p1 < ../openlane_spo_d1f0b60d7b31393ec0afb8f96e1ca02bb465b3fc.patch
+            true
+          else
+            echo "$0: Unable to patch" 1>&2
+            exit 1
+          fi
           git config --global user.email "darryl.miles.darrylmiles.org"
           git config --global user.name "Darryl L. Miles GHA"
           git commit -m "SPO antenna repair fix d1f0b60d7b31393ec0afb8f96e1ca02bb465b3fc" -a
@@ -237,7 +245,6 @@ jobs:
       - name: cleanup
         if: always()
         run: |
-          ls -l $HOME/.docker/config.json
-          dd if=/dev/zero bs=4k count=1 of=$HOME/.docker/config.json # chattr +s config.json
+          dd if=/dev/zero bs=4k count=1 status=none of=$HOME/.docker/config.json # chattr +s config.json
           rm -fv $HOME/.docker/config.json # paranoid cleanup
 
